name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: {{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: {{ vars.TURBO_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
